// Notification
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';

// Calculation
export const CALCULATE_FOR_ARGUMENTS_SUCCESS = 'CALCULATE_FOR_ARGUMENTS_SUCCESS';
export const CALCULATE_FOR_ARGUMENTS_ERROR = 'CALCULATE_FOR_ARGUMENTS_ERROR';